export const data=

{
    "Response": {
      "Activities": [],
      "Profile": {
        "FirstName": "Candace",
        "LastName": "Flynn",
        "PreferredLanguage": "en",
        "Timezone": "Eastern Standard Time",
        "CardholderTime": "2023-05-17T02:55:01.0001594",
        "LastSuccessfulLoginTime": "2023-05-17T02:54:41"
      },
      "Cards": [
        {
          "ProgramName": "smiONE North Dakota",
          "ExternalSVAID": "17200011",
          "Status": "ACTIVE",
          "SubStatus": "ACTIVE",
          "AccountTypeBit63": 1,
          "CardDisplayNumber": "xxxx7200",
          "AccountTypeName": "Primary",
          "Balance": 60.52,
          "OTB": 60.52,
          "LastBalanceUpdatedTime": "2019-08-25T12:14:08",
          "LastOTBUpdatedTime": "2019-08-25T12:14:08",
          "AllowFundTransfer": true,
          "ParentCardKey": 0,
          "AllowDeposits": true,
          "AllowLoadLocations": false,
          "AllowPayeeManagement": false,
          "AllowReferFriend": false,
          "AllowBillPayments": true,
          "FreshDeskDomain": "khumbuinformationsystems.freshdesk.com",
          "FreshDeskAppKey": "",
          "FreshDeskAppSecret": "",
          "FreshDeskCategoryID": "9000116554",
          "FreshDeskAPIKey": "49nNVWqXO3RPS2kwxgX",
          "IsReplaced": false,
          "AllowOrderNewCard": true,
          "EnableStatements": true,
          "BannerContent": "",
          "IsShared": false,
          "ShowPendingFees": true,
          "IngoCustID": "",
          "PaymentNetwork": "visa",
          "AllowRCD": true,
          "AllowSavings": false,
          "IsEnabledPushProvisioning": false,
          "AllowChat": true,
          "AllowPayPerks": true,
          "AllowReloadCash": true,
          "IsNewWebsiteAvailable": false,
          "ProgramKey": 112,
          "NameOnCard": "Candace Flynn",
          "ValidThru": "9999/12/31",
          "StatusCode": "ACT",
          "SubStatusCode": "ACT",
          "NewCardRequestedDate": "9999-12-31T00:00:00",
          "CardDesignID": 65,
          "CardKey": 720001,
          "NickName": "Candace - 7200"
        },
        {
          "ProgramName": "smiONE North Dakota",
          "ExternalSVAID": "17200021",
          "Status": "ACTIVE",
          "SubStatus": "ACTIVE",
          "AccountTypeBit63": 2,
          "CardDisplayNumber": "xxxx7201",
          "AccountTypeName": "Shared",
          "Balance": 60.52,
          "OTB": 60.52,
          "LastBalanceUpdatedTime": "2019-08-25T12:14:08",
          "LastOTBUpdatedTime": "2019-08-25T12:14:08",
          "AllowFundTransfer": false,
          "ParentCardKey": 720001,
          "AllowDeposits": false,
          "AllowLoadLocations": false,
          "AllowPayeeManagement": false,
          "AllowReferFriend": false,
          "AllowBillPayments": false,
          "FreshDeskDomain": "khumbuinformationsystems.freshdesk.com",
          "FreshDeskAppKey": "",
          "FreshDeskAppSecret": "",
          "FreshDeskCategoryID": "9000116554",
          "FreshDeskAPIKey": "49nNVWqXO3RPS2kwxgX",
          "IsReplaced": false,
          "AllowOrderNewCard": false,
          "EnableStatements": false,
          "BannerContent": "<p class=\"pMargin mobileVerification action\">Please click <a href=\"\" ng-click=\"verifyMobile($event)\">here</a> to verify your phone number.</p>",
          "IsShared": true,
          "ShowPendingFees": true,
          "IngoCustID": "",
          "PaymentNetwork": "visa",
          "AllowRCD": false,
          "AllowSavings": false,
          "IsEnabledPushProvisioning": false,
          "AllowChat": true,
          "AllowPayPerks": false,
          "AllowReloadCash": false,
          "IsNewWebsiteAvailable": false,
          "ProgramKey": 112,
          "NameOnCard": "Linda Flynn",
          "ValidThru": "9999/12/31",
          "StatusCode": "ACT",
          "SubStatusCode": "ACT",
          "NewCardRequestedDate": "9999-12-31T00:00:00",
          "CardDesignID": 65,
          "CardKey": 720002,
          "NickName": "Linda - 7201"
        },
        {
          "ProgramName": "smiONE North Dakota",
          "ExternalSVAID": "17200031",
          "Status": "ACTIVE",
          "SubStatus": "ACTIVE",
          "AccountTypeBit63": 8,
          "CardDisplayNumber": "xxxx7202",
          "AccountTypeName": "Nonshared",
          "Balance": 100.5,
          "OTB": 100.5,
          "LastBalanceUpdatedTime": "2023-05-08T23:20:28",
          "LastOTBUpdatedTime": "2023-05-08T23:20:28",
          "AllowFundTransfer": false,
          "ParentCardKey": 720001,
          "AllowDeposits": false,
          "AllowLoadLocations": false,
          "AllowPayeeManagement": false,
          "AllowReferFriend": false,
          "AllowBillPayments": true,
          "FreshDeskDomain": "khumbuinformationsystems.freshdesk.com",
          "FreshDeskAppKey": "",
          "FreshDeskAppSecret": "",
          "FreshDeskCategoryID": "9000116554",
          "FreshDeskAPIKey": "49nNVWqXO3RPS2kwxgX",
          "IsReplaced": false,
          "AllowOrderNewCard": false,
          "EnableStatements": true,
          "BannerContent": "<p class=\"pMargin mobileVerification action\">Please click <a href=\"\" ng-click=\"verifyMobile($event)\">here</a> to verify your phone number.</p>",
          "IsShared": false,
          "ShowPendingFees": true,
          "IngoCustID": "",
          "PaymentNetwork": "visa",
          "AllowRCD": false,
          "AllowSavings": false,
          "IsEnabledPushProvisioning": false,
          "AllowChat": true,
          "AllowPayPerks": false,
          "AllowReloadCash": false,
          "IsNewWebsiteAvailable": false,
          "ProgramKey": 112,
          "NameOnCard": "Stacy Flynn",
          "ValidThru": "9999/12/31",
          "StatusCode": "ACT",
          "SubStatusCode": "ACT",
          "NewCardRequestedDate": "9999-12-31T00:00:00",
          "CardDesignID": 65,
          "CardKey": 720003,
          "NickName": "Stacy - 7202"
        }
      ],
      "UtcTime": "2023-05-17T09:55:01.8151594Z"
    },
    "ResponseCode": 2000,
    "Messages": [],
    "Echo": {
      "RequestTime": "2023-05-17T09:55:00.9211556Z",
      "ResponseTime": "2023-05-17T09:55:01.8151594Z",
      "ITransactionID": "ae6d15ce-e160-4245-a0ed-110186e50785"
    }
  }