export const pendingFees=
{
    "Response": {
      "State": "success",
      "Message": "",
      "LastSyncTime": "9999-12-31T00:00:00",
      "PendingFees": [
        {
          "FeeId": "129",
          "FeeDate": "2023-03-23T22:01:52",
          "Amount": 2.5,
          "Description": "ATM withdrawal (out-of-network) Fee",
          "RelatedTransaction": {
            "Amount": 40,
            "Description": "ATM withdrawal (out-of-network)",
            "Date": "2019-06-04T03:59:24"
          },
          "FeeType": "PMD"
        },
        {
          "FeeId": "131",
          "FeeDate": "2023-02-07T22:01:52",
          "Amount": 2.5,
          "Description": "ATM withdrawal (out-of-network) Fee",
          "RelatedTransaction": {
            "Amount": 40,
            "Description": "ATM withdrawal (out-of-network)",
            "Date": "2019-04-04T03:59:24"
          },
          "FeeType": "PMD"
        },
        {
          "FeeId": "130",
          "FeeDate": "2023-01-13T22:01:52",
          "Amount": 0.5,
          "Description": "ATM Balance Inquiry Fee",
          "RelatedTransaction": {
            "Amount": 40,
            "Description": "ATM Balance Inquiry Fee",
            "Date": "2019-05-04T03:59:24"
          },
          "FeeType": "PMD"
        }
      ]
    },
    "ResponseCode": 2000,
    "Messages": [],
    "Echo": {
      "RequestTime": "2023-05-22T06:18:25.8373892Z",
      "ResponseTime": "2023-05-22T06:18:25.8546504Z",
      "ITransactionID": "a4cf4f12-44eb-4d4b-bc8e-7eb988e1f8c6"
    }
  } 


export const transactions=
{
    "Response": {
      "State": "success",
      "Message": "",
      "LastSyncTime": "9999-12-31T00:00:00",
      "TotalPages": 1,
      "Items": [
        {
          "TransactionID": 268500000000026,
          "TransactionTypeCode": "VSW",
          "Amount": 1.5,
          "CurrencyCode": "USD",
          "StatusCode": "APP",
          "Description": "SUNOCO 06115968 FORT MYERS - 7200",
          "TransactionTime": "2023-05-08T22:01:52",
          "MCCCode": "3351",
          "MerchantName": "SUNOCO 06115968 FORT MYERS",
          "ExternalStatus": "Pending",
          "Status": "Approved",
          "TypeDesc": "Pending",
          "IconUri": "https://money360-cardholder-service-ist.khumbusystems.net/api/icons?uri=default.png",
          "CreditedCardDisplayNumber": "",
          "DebitedCardDisplayNumber": "xxxx7200",
          "MccCategoryID": 5,
          "DrCrIndicator": "Dr",
          "TransactionReferenceNumber": "59901",
          "InternalRefNo": "59901",
          "TransactionType": "ATM Withdrawal",
          "AllowDispute": false,
          "Message": null
        },
        {
          "TransactionID": 268500000000027,
          "TransactionTypeCode": "PMFR",
          "Amount": 50,
          "CurrencyCode": "USD",
          "StatusCode": "APP",
          "Description": "WARSON GROUP INC, PAYROLL - 7200",
          "TransactionTime": "2023-05-08T22:01:52",
          "MCCCode": "0006",
          "MerchantName": "WARSON GROUP INC, PAYROLL",
          "ExternalStatus": "Pending",
          "Status": "Approved",
          "TypeDesc": "Pending",
          "IconUri": "https://money360-cardholder-service-ist.khumbusystems.net/api/icons?uri=default.png",
          "CreditedCardDisplayNumber": "xxxx7200",
          "DebitedCardDisplayNumber": "",
          "MccCategoryID": 23,
          "DrCrIndicator": "Cr",
          "TransactionReferenceNumber": "83223",
          "InternalRefNo": "83223",
          "TransactionType": "Direct Deposit",
          "AllowDispute": false,
          "Message": null
        },
        {
          "TransactionID": 268300000000022,
          "TransactionTypeCode": "PLA",
          "Amount": 30.2,
          "CurrencyCode": "USD",
          "StatusCode": "APP",
          "Description": "Wal-Mart Super Center LABELLE - 7200",
          "TransactionTime": "2023-05-06T22:01:52",
          "MCCCode": "5411",
          "MerchantName": "Wal-Mart Super Center LABELLE",
          "ExternalStatus": "Pending",
          "Status": "Approved",
          "TypeDesc": "Pending",
          "IconUri": "https://money360-cardholder-service-ist.khumbusystems.net/api/icons?uri=default.png",
          "CreditedCardDisplayNumber": "",
          "DebitedCardDisplayNumber": "xxxx7200",
          "MccCategoryID": 12,
          "DrCrIndicator": "Dr",
          "TransactionReferenceNumber": "83223",
          "InternalRefNo": "83223",
          "TransactionType": "Purchase with PIN",
          "AllowDispute": false,
          "Message": null
        },
        {
          "TransactionID": 268100000000025,
          "TransactionTypeCode": "SDC",
          "Amount": 21.5,
          "CurrencyCode": "USD",
          "StatusCode": "APP",
          "Description": "HEB #543 COLLEGE STATI - 7200",
          "TransactionTime": "2023-05-04T22:01:52",
          "MCCCode": "7641",
          "MerchantName": "HEB #543 COLLEGE STATI",
          "ExternalStatus": "Pending",
          "Status": "Approved",
          "TypeDesc": "Pending",
          "IconUri": "https://money360-cardholder-service-ist.khumbusystems.net/api/icons?uri=default.png",
          "CreditedCardDisplayNumber": "",
          "DebitedCardDisplayNumber": "xxxx7200",
          "MccCategoryID": 11,
          "DrCrIndicator": "Dr",
          "TransactionReferenceNumber": "83223",
          "InternalRefNo": "83223",
          "TransactionType": "Pre-auth completion",
          "AllowDispute": false,
          "Message": null
        },
        {
          "TransactionID": 268000000000024,
          "TransactionTypeCode": "ISA",
          "Amount": 14.52,
          "CurrencyCode": "USD",
          "StatusCode": "APP",
          "Description": "SHOP N GO COLLEGE STATI - 7200",
          "TransactionTime": "2023-05-03T22:01:52",
          "MCCCode": "5499",
          "MerchantName": "SHOP N GO COLLEGE STATI",
          "ExternalStatus": "Pending",
          "Status": "Approved",
          "TypeDesc": "Pending",
          "IconUri": "https://money360-cardholder-service-ist.khumbusystems.net/api/icons?uri=default.png",
          "CreditedCardDisplayNumber": "",
          "DebitedCardDisplayNumber": "xxxx7200",
          "MccCategoryID": 12,
          "DrCrIndicator": "Dr",
          "TransactionReferenceNumber": "83223",
          "InternalRefNo": "83223",
          "TransactionType": "Purchase with PIN",
          "AllowDispute": false,
          "Message": null
        },
        {
          "TransactionID": 267800000000023,
          "TransactionTypeCode": "SDA",
          "Amount": 20,
          "CurrencyCode": "USD",
          "StatusCode": "APP",
          "Description": "SHOP N GO COLLEGE STATI - 7200",
          "TransactionTime": "2023-05-01T22:01:52",
          "MCCCode": "0006",
          "MerchantName": "SHOP N GO COLLEGE STATI",
          "ExternalStatus": "Pending",
          "Status": "Approved",
          "TypeDesc": "Pending",
          "IconUri": "https://money360-cardholder-service-ist.khumbusystems.net/api/icons?uri=default.png",
          "CreditedCardDisplayNumber": "",
          "DebitedCardDisplayNumber": "xxxx7200",
          "MccCategoryID": 23,
          "DrCrIndicator": "Dr",
          "TransactionReferenceNumber": "59901",
          "InternalRefNo": "59901",
          "TransactionType": "Purchase with PIN",
          "AllowDispute": false,
          "Message": null
        },
        {
          "TransactionID": 268500000000020,
          "TransactionTypeCode": "VSW",
          "Amount": 4.5,
          "CurrencyCode": "USD",
          "StatusCode": "STL",
          "Description": "SUNOCO 06115968 FORT MYERS - 7200",
          "TransactionTime": "2023-05-08T22:01:52",
          "MCCCode": "3351",
          "MerchantName": "SUNOCO 06115968 FORT MYERS",
          "ExternalStatus": "Completed",
          "Status": "Completed",
          "TypeDesc": "",
          "IconUri": "https://money360-cardholder-service-ist.khumbusystems.net/api/icons?uri=default.png",
          "CreditedCardDisplayNumber": "",
          "DebitedCardDisplayNumber": "xxxx7200",
          "MccCategoryID": 5,
          "DrCrIndicator": "Dr",
          "TransactionReferenceNumber": "59901",
          "InternalRefNo": "59901",
          "TransactionType": "ATM Withdrawal",
          "AllowDispute": false,
          "Message": null
        },
        {
          "TransactionID": 268400000000016,
          "TransactionTypeCode": "PLA",
          "Amount": 6.6,
          "CurrencyCode": "USD",
          "StatusCode": "STL",
          "Description": "Wal-Mart Super Center LABELLE - 7200",
          "TransactionTime": "2023-05-07T22:01:52",
          "MCCCode": "5411",
          "MerchantName": "Wal-Mart Super Center LABELLE",
          "ExternalStatus": "Completed",
          "Status": "Completed",
          "TypeDesc": "",
          "IconUri": "https://money360-cardholder-service-ist.khumbusystems.net/api/icons?uri=default.png",
          "CreditedCardDisplayNumber": "",
          "DebitedCardDisplayNumber": "xxxx7200",
          "MccCategoryID": 12,
          "DrCrIndicator": "Dr",
          "TransactionReferenceNumber": "83223",
          "InternalRefNo": "83223",
          "TransactionType": "Purchase with PIN",
          "AllowDispute": false,
          "Message": null
        },
        {
          "TransactionID": 268300000000018,
          "TransactionTypeCode": "ISL",
          "Amount": 5.52,
          "CurrencyCode": "USD",
          "StatusCode": "STL",
          "Description": "SHOP N GO COLLEGE STATI - 7200",
          "TransactionTime": "2023-05-06T22:01:52",
          "MCCCode": "5411",
          "MerchantName": "SHOP N GO COLLEGE STATI",
          "ExternalStatus": "Completed",
          "Status": "Completed",
          "TypeDesc": "",
          "IconUri": "https://money360-cardholder-service-ist.khumbusystems.net/api/icons?uri=default.png",
          "CreditedCardDisplayNumber": "",
          "DebitedCardDisplayNumber": "xxxx7200",
          "MccCategoryID": 12,
          "DrCrIndicator": "Dr",
          "TransactionReferenceNumber": "83223",
          "InternalRefNo": "83223",
          "TransactionType": "Auth",
          "AllowDispute": false,
          "Message": null
        },
        {
          "TransactionID": 268200000000019,
          "TransactionTypeCode": "SDC",
          "Amount": 6.2,
          "CurrencyCode": "USD",
          "StatusCode": "STL",
          "Description": "HEB #543 COLLEGE STATI - 7200",
          "TransactionTime": "2023-05-05T22:01:52",
          "MCCCode": "7641",
          "MerchantName": "HEB #543 COLLEGE STATI",
          "ExternalStatus": "Completed",
          "Status": "Completed",
          "TypeDesc": "",
          "IconUri": "https://money360-cardholder-service-ist.khumbusystems.net/api/icons?uri=default.png",
          "CreditedCardDisplayNumber": "",
          "DebitedCardDisplayNumber": "xxxx7200",
          "MccCategoryID": 11,
          "DrCrIndicator": "Dr",
          "TransactionReferenceNumber": "83223",
          "InternalRefNo": "83223",
          "TransactionType": "Pre-auth completion",
          "AllowDispute": false,
          "Message": null
        },
        {
          "TransactionID": 268000000000021,
          "TransactionTypeCode": "PMFR",
          "Amount": 30.71,
          "CurrencyCode": "USD",
          "StatusCode": "STL",
          "Description": "FSPC Support Payment - 7200",
          "TransactionTime": "2023-05-03T22:01:52",
          "MCCCode": "0006",
          "MerchantName": "FSPC Support Payment",
          "ExternalStatus": "Completed",
          "Status": "Completed",
          "TypeDesc": "",
          "IconUri": "https://money360-cardholder-service-ist.khumbusystems.net/api/icons?uri=default.png",
          "CreditedCardDisplayNumber": "xxxx7200",
          "DebitedCardDisplayNumber": "",
          "MccCategoryID": 23,
          "DrCrIndicator": "Cr",
          "TransactionReferenceNumber": "83223",
          "InternalRefNo": "83223",
          "TransactionType": "Direct Deposit",
          "AllowDispute": false,
          "Message": null
        },
        {
          "TransactionID": 267900000000017,
          "TransactionTypeCode": "SDA",
          "Amount": 11.1,
          "CurrencyCode": "USD",
          "StatusCode": "STL",
          "Description": "SHOP N GO COLLEGE STATI - 7200",
          "TransactionTime": "2023-05-02T22:01:52",
          "MCCCode": "0006",
          "MerchantName": "SHOP N GO COLLEGE STATI",
          "ExternalStatus": "Completed",
          "Status": "Completed",
          "TypeDesc": "",
          "IconUri": "https://money360-cardholder-service-ist.khumbusystems.net/api/icons?uri=default.png",
          "CreditedCardDisplayNumber": "",
          "DebitedCardDisplayNumber": "xxxx7200",
          "MccCategoryID": 23,
          "DrCrIndicator": "Dr",
          "TransactionReferenceNumber": "59901",
          "InternalRefNo": "59901",
          "TransactionType": "Purchase with PIN",
          "AllowDispute": false,
          "Message": null
        }
      ],
      "TotalItemsCount": 12,
      "CurrentPage": 1,
      "RowsPerPage": 12
    },
    "ResponseCode": 2000,
    "Messages": [],
    "Echo": {
      "RequestTime": "2023-05-22T06:32:05.5913913Z",
      "ResponseTime": "2023-05-22T06:32:05.6382656Z",
      "ITransactionID": "f7d8394f-c726-4566-b3e0-fa9396962fcd"
    }
  }